// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lohlusmlbepnrkeaetwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvaGx1c21sYmVwbnJrZWFldHdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2Mzg5MDAsImV4cCI6MjA1NjIxNDkwMH0.raupYzxXVR64ORzlVjTfkH2w_QBe5yp9ILnVl7a0VQU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);